In [2]:
import numpy as np 
import time 

In [3]:
size=1_00_000
py_list=list(range(size))
st=time.time()
sq_list=[x ** 2 for x in py_list]
end=time.time()
print(f"Total time taken for list={end-st}")
np_arr=np.array(py_list)
st=time.time()
sq_arr=np_arr ** 2
end=time.time()
print(f"Total time taken for np array={end-st}")

Total time taken for list=0.007304191589355469
Total time taken for np array=0.0013885498046875


In [4]:
import sys
print(f"SIze of list={sys.getsizeof(py_list)*len(py_list)}")
print(f"SIze of np arr={np_arr.nbytes}")

SIze of list=80005600000
SIze of np arr=800000


In [5]:
nd_arr=np.array([1,2,3,4,5])
print(nd_arr,nd_arr.shape)
twod_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod_arr,twod_arr.shape)

[1 2 3 4 5] (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [6]:
arr1=np.zeros((3,4)) #array of zeros
print(arr1)
arr2=np.ones((3,4)) #array of ones
print(arr2)
arr3=np.eye((3)) #Identity matrix
print(arr3)
arr4=np.arange(1,10,2) #Ranged elements
print(arr4)
arr5=np.full((3,4),100) #prefill with value
print(arr5)
arr6=np.linspace(1,100,3) #array of zeros
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[  1.   50.5 100. ]


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape) #shows the m x n dimension
print(arr.size) #shows no of elements
print(arr.dtype) #shows the data type
print(arr.ndim) #shows the n dimension

#type conversion
arr_zero=np.zeros((2,3), dtype="int64") 
print(arr_zero)
float_array=arr_zero.astype(np.float64)
print(float_array)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64
2
[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Operations on Array 
arr=np.array([1,2,3,4,5,6])
print(arr)
reshaped_arr=arr.reshape((2,3)) #reshapes into a 2 x 2 matrix
print(reshaped_arr)
flattened_arr=arr.flatten() #flattens into 1D array
print(flattened_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [9]:
# Indexing
arr = np.array([1, 2, 3, 4, 5]) #1D array
print(arr[0])
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) #2D array
print(arr[0][1]) #2
print(arr[1][2]) #6
#Fancy indexing
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 4]
print(arr[idx])
#Boolean indexing
print(arr[arr > 2]) #nums greater than 2
print(arr[arr % 2 == 0]) #even nums

1
2
6
[1 2 5]
[3 4 5]
[2 4]


In [10]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[2:6]) 
print(arr[:6]) 
print(arr[3:]) 
print(arr[::2]) 

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


In [11]:
#copy vs view
arr=[1,2,3,4,5]
sub_arr=arr[1:4]
print(sub_arr)
sub_arr[0]=200
print(arr) #original list remains same 
arr_np=np.array(arr)
sub_arr_np=arr_np[1:4]
print(sub_arr_np)
sub_arr_np[0]=200
print(arr_np) #oroginal array gets changed 

[2, 3, 4]
[1, 2, 3, 4, 5]
[2 3 4]
[  1 200   3   4   5]


In [12]:
#Axes in 2d and 3d arrays
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.shape)
sum_of_rows=np.sum(arr2d,axis=1)
sum_of_columns=np.sum(arr2d,axis=0)
print(f"Sum iof rows={sum_of_rows},Sum of columns={sum_of_columns}")
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr3d,arr3d.shape)
print(arr3d[0,1,1]) #prints 5
print(arr3d[:,:,1]) #prints 2nd column of both mat 
arr3d[:,:,1]=99
print(arr3d) #updates the value of all elemnts of 2nd column of both matrix to 99

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
Sum iof rows=[ 6 15 24],Sum of columns=[12 15 18]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] (2, 3, 3)
5
[[ 2  5  8]
 [11 14 17]]
[[[ 1 99  3]
  [ 4 99  6]
  [ 7 99  9]]

 [[10 99 12]
  [13 99 15]
  [16 99 18]]]


In [17]:
#Vectorisation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1 **2) #sqaures every element
print(arr1+arr)
print(arr1 + 10)#adds 10 to every elementarr3
#Broadcasting
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1+arr3)
arr4=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr3+arr4) #not possible bcox 2x5 array and 3x5 array not comp.


[ 1  4  9 16 25]
[ 2  4  6  8 10]
[11 12 13 14 15]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


ValueError: operands could not be broadcast together with shapes (2,5) (3,5) 

In [19]:
#normalization 
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr) 
std_dev=np.std(arr)
normalized_arr=(arr-mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [21]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0

#Power Functions
print(np.square(arr))    # [1, 4, 9, 16, 25]
print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))    # [1, 8, 27, 64, 125]

#Log and exp funcs
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

#Rounding functions
print(np.round(2.678))    # 3.0
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0
print(np.trunc(2.678))    # 2.0

#Additional functions
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
2.0
3.0
2.0
[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
